export const chatsData = [
  {
    id: 1,
    name: 'Андрей',
    lastMessage: 'Изображение',
    time: '10:49',
    unreadCount: 2,
    avatar: null,
  },
  {
    id: 2,
    name: 'Киноклуб',
    lastMessage: 'Вы: стикер',
    time: '12:00',
    unreadCount: 0,
    avatar: null,
  },
  {
    id: 3,
    name: 'Илья',
    lastMessage: 'Друзья, у меня для вас особенный выпуск новостей!...',
    time: '15:12',
    unreadCount: 4,
    avatar: null,
  },
  {
    id: 4,
    name: 'Вадим',
    lastMessage: 'Вы: Круто!',
    time: 'Пт',
    unreadCount: 0,
    isActive: true,
    avatar: null,
  },
  {
    id: 5,
    name: 'Мария',
    lastMessage: 'Спасибо, всё получила.',
    time: 'Вчера',
    unreadCount: 1,
    avatar: null,
  },
  {
    id: 6,
    name: 'Рабочий чат',
    lastMessage: 'Созвонимся в 11:30.',
    time: '09:10',
    unreadCount: 3,
    avatar: null,
  },
  {
    id: 7,
    name: 'Мама',
    lastMessage: 'Когда приедешь?',
    time: '08:45',
    unreadCount: 0,
    avatar: null,
  },
  {
    id: 8,
    name: 'Папа',
    lastMessage: 'Посмотри новости, там про это говорят.',
    time: 'Вчера',
    unreadCount: 0,
    avatar: null,
  },
  {
    id: 9,
    name: 'Сергей',
    lastMessage: 'Ок, договорились.',
    time: 'Чт',
    unreadCount: 2,
    avatar: null,
  },
  {
    id: 10,
    name: 'Доставка',
    lastMessage: 'Курьер уже у вашего подъезда.',
    time: '11:05',
    unreadCount: 0,
    avatar: null,
  },
  {
    id: 11,
    name: 'Алексей',
    lastMessage: 'Кинь, пожалуйста, архив с проектом.',
    time: 'Пн',
    unreadCount: 1,
    avatar: null,
  },
  {
    id: 12,
    name: 'Команда фронта',
    lastMessage: 'Выложил ветку с фиксом.',
    time: '16:22',
    unreadCount: 5,
    avatar: null,
  },
  {
    id: 13,
    name: 'Офис',
    lastMessage: 'Завтра сокращённый день.',
    time: 'Пт',
    unreadCount: 0,
    avatar: null,
  },
  {
    id: 14,
    name: 'Группа курса',
    lastMessage: 'Вот ссылка на запись лекции.',
    time: 'Вчера',
    unreadCount: 7,
    avatar: null,
  },
  {
    id: 15,
    name: 'Денис',
    lastMessage: 'Ща подойду.',
    time: '13:48',
    unreadCount: 0,
    avatar: null,
  },
  {
    id: 16,
    name: 'Антон',
    lastMessage: 'Там в задаче есть нюанс...',
    time: '11:32',
    unreadCount: 2,
    avatar: null,
  },
  {
    id: 17,
    name: 'Фитнес',
    lastMessage: 'Тренировка перенесена на 19:00.',
    time: 'Сегодня',
    unreadCount: 1,
    avatar: null,
  },
  {
    id: 18,
    name: 'Кофейня рядом',
    lastMessage: 'Ваша скидка активна до конца недели.',
    time: 'Пн',
    unreadCount: 0,
    avatar: null,
  },
  {
    id: 19,
    name: 'ЖКХ',
    lastMessage: 'Передайте показания до 25 числа.',
    time: 'Ср',
    unreadCount: 0,
    avatar: null,
  },
  {
    id: 20,
    name: 'Банк',
    lastMessage: 'Поступление на карту 3 200 ₽.',
    time: '09:01',
    unreadCount: 0,
    avatar: null,
  },
  {
    id: 21,
    name: 'Соседи',
    lastMessage: 'Можно перенести встречу на завтра?',
    time: 'Вчера',
    unreadCount: 3,
    avatar: null,
  },
  {
    id: 22,
    name: 'Артём',
    lastMessage: 'Го кататься на выходных.',
    time: 'Чт',
    unreadCount: 0,
    avatar: null,
  },
  {
    id: 23,
    name: 'Лена',
    lastMessage: 'Фото просто огонь!',
    time: 'Сб',
    unreadCount: 1,
    avatar: null,
  },
  {
    id: 24,
    name: 'Книжный клуб',
    lastMessage: 'В этот раз читаем Пелевина.',
    time: 'Пн',
    unreadCount: 4,
    avatar: null,
  },
  {
    id: 25,
    name: 'Такси',
    lastMessage: 'Ваше такси подано.',
    time: '22:13',
    unreadCount: 0,
    avatar: null,
  },
  {
    id: 26,
    name: 'Игровой чат',
    lastMessage: 'Сегодня рейд в 21:00.',
    time: 'Сегодня',
    unreadCount: 6,
    avatar: null,
  },
  {
    id: 27,
    name: 'Проект A',
    lastMessage: 'Запушил MR, посмотри, пожалуйста.',
    time: '11:57',
    unreadCount: 2,
    avatar: null,
  },
  {
    id: 28,
    name: 'Проект B',
    lastMessage: 'Создал тикет по багу.',
    time: 'Вчера',
    unreadCount: 0,
    avatar: null,
  },
  {
    id: 29,
    name: 'Группа универа',
    lastMessage: 'Зачёт перенесли.',
    time: 'Ср',
    unreadCount: 3,
    avatar: null,
  },
  {
    id: 30,
    name: 'Катя',
    lastMessage: 'Я на месте.',
    time: '19:40',
    unreadCount: 0,
    avatar: null,
  },
  {
    id: 31,
    name: 'Максим',
    lastMessage: 'Скинь, пожалуйста, ТЗ ещё раз.',
    time: '12:34',
    unreadCount: 1,
    avatar: null,
  },
  {
    id: 32,
    name: 'HR',
    lastMessage: 'Пришлите, пожалуйста, актуальное резюме.',
    time: 'Пт',
    unreadCount: 0,
    avatar: null,
  },
  {
    id: 33,
    name: 'Курс по Vue',
    lastMessage: 'Вышел новый модуль по тестированию.',
    time: 'Сегодня',
    unreadCount: 5,
    avatar: null,
  },
  {
    id: 34,
    name: 'Оповещения GitHub',
    lastMessage: 'Новый комментарий к pull request.',
    time: '09:55',
    unreadCount: 4,
    avatar: null,
  },
  {
    id: 35,
    name: 'Техподдержка',
    lastMessage: 'Ваш запрос принят в работу.',
    time: 'Вчера',
    unreadCount: 0,
    avatar: null,
  },
  {
    id: 36,
    name: 'СберМаркет',
    lastMessage: 'Заказ оформлен, ожидайте подтверждения.',
    time: '11:18',
    unreadCount: 0,
    avatar: null,
  },
  {
    id: 37,
    name: 'Notify бот',
    lastMessage: 'Сборка в CI упала.',
    time: '10:02',
    unreadCount: 2,
    avatar: null,
  },
  {
    id: 38,
    name: 'Автосервис',
    lastMessage: 'Машина будет готова к 18:00.',
    time: 'Ср',
    unreadCount: 0,
    avatar: null,
  },
  {
    id: 39,
    name: 'Коля',
    lastMessage: 'Новый мем видел?',
    time: '23:15',
    unreadCount: 1,
    avatar: null,
  },
  {
    id: 40,
    name: 'Тестовый чат',
    lastMessage: 'Сообщение для проверки верстки списка.',
    time: 'Сегодня',
    unreadCount: 9,
    avatar: null,
  },
];

export const chatPageData = {
  currentChat: {
    id: 4,
    name: 'Вадим',
    date: '19 июня',
  },
  messages: [
    {
      id: 1,
      isOutgoing: false,
      text: 'Привет! Смотри, тут всплыл интересный кусок лунной космической истории — НАСА в какой-то момент попросила Хассельблад адаптировать модель SWC для полетов на Луну. Сейчас мы все знаем, что астронавты летали с моделью 500 EL — и, к слову говоря, все тушки этих камер все еще находятся на поверхности Луны, так как астронавты с собой забрали только кассеты с пленкой.\n\nХассельблад в итоге адаптировал SWC для космоса, но что-то пошло не так и на ракету они так никогда и не попали. Всего их было произведено 25 штук, одну из них недавно продали на аукционе за 45000 евро.',
      time: '11:56',
    },
    {
      id: 2,
      isOutgoing: false,
      image: '../../../static/img/Camera.svg',
      imageAlt: 'Камера',
      time: '11:56',
    },
    {
      id: 3,
      isOutgoing: true,
      text: 'Круто!',
      time: '12:00',
      status: '✓✓',
    },
  ],
};

